USE kiwbxw4e3dt7q258;

INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('CA', 'calcium');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('CHOCDF', 'carbs');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('CHOLE', 'cholesterol');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('FAMS', 'monounsaturated');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('FAPU', 'polyunsatured');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('FASAT', 'saturated');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('FAT', 'fat');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('FATRN', 'trans'); 
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('FE', 'iron');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('FIBTG', 'fiber');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('FOLDFE', 'folate');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('K', 'potassium');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('MG', 'magnesium');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('NA', 'sodium');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('KCAL', 'energy');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('NIA', 'niacin');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('P', 'phosphorus');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('PROCNT', 'protein');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('RIBF', 'riboflavin');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('SUGAR', 'sugars');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('THIA', 'thiamin');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('TOCPHA', 'vitamin E');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('VITA_RAE', 'vitamin A');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('VITB12', 'vitamin B12');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('VITB6A', 'vitamin B6');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('VITC', 'vitamin C');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('VITD', 'vitamin D');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('VITK1', 'vitamin K');
INSERT INTO Nutrients (nutrientApiCode, nutrientName) VALUES ('ZN', 'zinc');